version: '3'
services:
  red1:
    build:
      context: ../../colorapp
    command: ['Red 1','red', 'http://blue2:8080']
    privileged: true
    ports:
      - "18080:8080"
    volumes:
      - "../logs/red1:/var/log/envoy"
      - "./:/etc/envoy:ro"
    networks:
      - color
  red2:
    build:
      context: ../../colorapp
    command: ['Red 2','red']
    privileged: true
    ports:
      - "28080:8080"
    volumes:
      - "../logs/red2:/var/log/envoy"
      - "./:/etc/envoy:ro"
    networks:
      - color

  blue1:
    build:
      context: ../../colorapp
    command: ['Blue 1','blue', 'http://red2:8080']
    privileged: true
    ports:
      - "18081:8080"
    volumes:
      - "../logs/blue1:/var/log/envoy"
      - "./:/etc/envoy:ro"
    networks:
      - color
  blue2:
    build:
      context: ../../colorapp
    command: ['Blue 2','blue']
    privileged: true
    ports:
      - "28081:8080"
    volumes:
      - "../logs/blue2:/var/log/envoy"
      - "./:/etc/envoy:ro"
    networks:
      - color

  ui:
    build:
      context: ../../colorui
    command: ['http://red1:8080', 'http://blue1:8080']
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - "../logs/ui:/var/log/envoy"
      - "./:/etc/envoy:ro"
    networks:
      - color

networks:
  color:
