version: '3'
services:
  red1:
    build:
      context: ../../colorapp
      dockerfile: Dockerfile.v1
    command: ['Red 1','red', 'http://blue2:8080']
    ports:
      - "18080:8080"
    networks:
      - color
  red2:
    build:
      context: ../../colorapp
      dockerfile: Dockerfile.v1
    command: ['Red 2','red']
    ports:
      - "28080:8080"
    networks:
      - color

  blue1:
    build:
      context: ../../colorapp
      dockerfile: Dockerfile.v1
    command: ['Blue 1','blue', 'http://red2:8080']
    ports:
      - "18081:8080"
    networks:
      - color
  blue2:
    build:
      context: ../../colorapp
      dockerfile: Dockerfile.v1
    command: ['Blue 2','blue']
    ports:
      - "28081:8080"
    networks:
      - color

  ui:
    build:
      context: ../../colorui
      dockerfile: Dockerfile.v1
    command: ['http://red1:8080', 'http://blue1:8080']
    ports:
      - "8080:8080"
    networks:
      - color

networks:
  color:
