// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package main

import (
	v2 "github.com/envoyproxy/go-control-plane/envoy/api/v2"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Clusters struct {
	Clusters             []*v2.Cluster `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Clusters) Reset()         { *m = Clusters{} }
func (m *Clusters) String() string { return proto.CompactTextString(m) }
func (*Clusters) ProtoMessage()    {}
func (*Clusters) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *Clusters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Clusters.Unmarshal(m, b)
}
func (m *Clusters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Clusters.Marshal(b, m, deterministic)
}
func (m *Clusters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Clusters.Merge(m, src)
}
func (m *Clusters) XXX_Size() int {
	return xxx_messageInfo_Clusters.Size(m)
}
func (m *Clusters) XXX_DiscardUnknown() {
	xxx_messageInfo_Clusters.DiscardUnknown(m)
}

var xxx_messageInfo_Clusters proto.InternalMessageInfo

func (m *Clusters) GetClusters() []*v2.Cluster {
	if m != nil {
		return m.Clusters
	}
	return nil
}

type Routes struct {
	Routes               []*v2.RouteConfiguration `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Routes) Reset()         { *m = Routes{} }
func (m *Routes) String() string { return proto.CompactTextString(m) }
func (*Routes) ProtoMessage()    {}
func (*Routes) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *Routes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Routes.Unmarshal(m, b)
}
func (m *Routes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Routes.Marshal(b, m, deterministic)
}
func (m *Routes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Routes.Merge(m, src)
}
func (m *Routes) XXX_Size() int {
	return xxx_messageInfo_Routes.Size(m)
}
func (m *Routes) XXX_DiscardUnknown() {
	xxx_messageInfo_Routes.DiscardUnknown(m)
}

var xxx_messageInfo_Routes proto.InternalMessageInfo

func (m *Routes) GetRoutes() []*v2.RouteConfiguration {
	if m != nil {
		return m.Routes
	}
	return nil
}

func init() {
	proto.RegisterType((*Clusters)(nil), "main.Clusters")
	proto.RegisterType((*Routes)(nil), "main.Routes")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0x2c, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x93, 0x12, 0x4b, 0xcd,
	0x2b, 0xcb, 0xaf, 0xd4, 0x4f, 0x2c, 0xc8, 0xd4, 0x2f, 0x33, 0xd2, 0x4f, 0x4e, 0x29, 0x86, 0xc8,
	0xa2, 0x89, 0x17, 0xc1, 0xc4, 0x95, 0x6c, 0xb9, 0x38, 0x9c, 0x73, 0x4a, 0x8b, 0x4b, 0x52, 0x8b,
	0x8a, 0x85, 0x0c, 0xb9, 0x38, 0x92, 0xa1, 0x6c, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x51,
	0x3d, 0xb0, 0x36, 0xbd, 0xc4, 0x82, 0x4c, 0xbd, 0x32, 0x23, 0x3d, 0xa8, 0xca, 0x20, 0xb8, 0x32,
	0x25, 0x27, 0x2e, 0xb6, 0xa0, 0xfc, 0xd2, 0x92, 0xd4, 0x62, 0x21, 0x0b, 0x2e, 0xb6, 0x22, 0x30,
	0x0b, 0xaa, 0x55, 0x01, 0x55, 0x2b, 0x58, 0x95, 0x73, 0x7e, 0x5e, 0x5a, 0x66, 0x7a, 0x69, 0x51,
	0x62, 0x49, 0x66, 0x7e, 0x5e, 0x10, 0x54, 0x7d, 0x12, 0x1b, 0xd8, 0x25, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xd9, 0xb0, 0xea, 0x37, 0xcd, 0x00, 0x00, 0x00,
}
