version: '3'
services:
  red1:
    build:
      context: ../../colorapp
      dockerfile: Dockerfile.v2
    command: ['Red 1','red', 'http://blue:8080']
    privileged: true
    volumes:
      - "../logs/red1:/var/log/envoy"
      - "./:/etc/envoy:ro"
    extra_hosts:
      - "blue:127.0.0.1"
      - "red:127.0.0.1"
    networks:
      - color

  red2:
    build:
      context: ../../colorapp
      dockerfile: Dockerfile.v2
    command: ['Red 2','red']
    privileged: true
    volumes:
      - "../logs/red2:/var/log/envoy"
      - "./:/etc/envoy:ro"
    extra_hosts:
      - "blue:127.0.0.1"
      - "red:127.0.0.1"
    networks:
      - color

  blue1:
    build:
      context: ../../colorapp
      dockerfile: Dockerfile.v2
    command: ['Blue 1','blue', 'http://red:8080']
    privileged: true
    volumes:
      - "../logs/blue1:/var/log/envoy"
      - "./:/etc/envoy:ro"
    extra_hosts:
      - "blue:127.0.0.1"
      - "red:127.0.0.1"
    networks:
      - color

  blue2:
    build:
      context: ../../colorapp
      dockerfile: Dockerfile.v2
    command: ['Blue 2','blue']
    privileged: true
    volumes:
      - "../logs/blue2:/var/log/envoy"
      - "./:/etc/envoy:ro"
    extra_hosts:
      - "blue:127.0.0.1"
      - "red:127.0.0.1"
    networks:
      - color

  ui:
    build:
      context: ../../colorui
      dockerfile: Dockerfile.v2
    command: ['http://red:8080', 'http://blue:8080']
    privileged: true
    ports:
      - "8080:8080"
      - "15000:15000"
    volumes:
      - "../logs/ui:/var/log/envoy"
      - "./:/etc/envoy:ro"
    extra_hosts:
      - "blue:127.0.0.1"
      - "red:127.0.0.1"
    networks:
      - color

networks:
  color:
