---
admin:
  access_log_path: /var/log/envoy/admin_access.log
  address:
    socket_address: {address: "0.0.0.0", port_value: 15000}

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: {address: "0.0.0.0", port_value: 15001}
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO
                route_config:
                  name: static
                  virtual_hosts:
                    - name: ui
                      domains: ["ui:8080"]
                      routes:
                        - match: {prefix: "/"}
                          route: {cluster: ui}
                    - name: red
                      domains: ["red:8080"]
                      routes:
                        - match: {prefix: "/"}
                          route: {cluster: red}
                    - name: blue
                      domains: ["blue:8080"]
                      routes:
                        - match: {prefix: "/"}
                          route: {cluster: blue}
                http_filters:
                  - name: envoy.router
                access_log:
                  - name: envoy.file_access_log
                    config:
                      path: /var/log/envoy/access.log
  clusters:
    - name: ui
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: ui
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: ui
                      port_value: 8080
    - name: red
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: red
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: red1
                      port_value: 8080
              - endpoint:
                  address:
                    socket_address:
                      address: red2
                      port_value: 8080
    - name: blue
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: blue
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: blue1
                      port_value: 8080
              - endpoint:
                  address:
                    socket_address:
                      address: blue2
                      port_value: 8080
