version: '3'
services:
  red1:
    build:
      context: ../../colorapp
      dockerfile: Dockerfile.v3
    command: ['Red 1','red', 'http://blue.srv:8080']
    privileged: true
    volumes:
      - "../logs/red1:/var/log/envoy"
      - "./:/etc/envoy:ro"
    networks:
      - color

  red2:
    build:
      context: ../../colorapp
      dockerfile: Dockerfile.v3
    command: ['Red 2','red']
    privileged: true
    volumes:
      - "../logs/red2:/var/log/envoy"
      - "./:/etc/envoy:ro"
    networks:
      - color

  blue1:
    build:
      context: ../../colorapp
      dockerfile: Dockerfile.v3
    command: ['Blue 1','blue', 'http://red.srv:8080']
    privileged: true
    volumes:
      - "../logs/blue1:/var/log/envoy"
      - "./:/etc/envoy:ro"
    networks:
      - color

  blue2:
    build:
      context: ../../colorapp
      dockerfile: Dockerfile.v3
    command: ['Blue 2','blue']
    privileged: true
    volumes:
      - "../logs/blue2:/var/log/envoy"
      - "./:/etc/envoy:ro"
    networks:
      - color

  ui:
    build:
      context: ../../colorui
      dockerfile: Dockerfile.v3
    command: ['http://red.srv:8080', 'http://blue.srv:8080']
    privileged: true
    ports:
      - "8080:8080"
      - "15000:15000"
    volumes:
      - "../logs/ui:/var/log/envoy"
      - "./:/etc/envoy:ro"
    networks:
      - color

  control:
    build:
      context: ../../control
      dockerfile: Dockerfile
    command: ['/etc/envoy/cluster.yaml', '/etc/envoy/routes.yaml']
    volumes:
      - "./:/etc/envoy:ro"
    networks:
      - color

networks:
  color:
