---
admin:
  access_log_path: /var/log/envoy/admin_access.log
  address:
    socket_address: {address: "0.0.0.0", port_value: 15000}

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: {address: "0.0.0.0", port_value: 15001}
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO
                rds:
                  route_config_name: dynamic
                  config_source:
                    api_config_source:
                      api_type: GRPC
                      grpc_services:
                        envoy_grpc:
                          cluster_name: control
                http_filters:
                  - name: envoy.router
                access_log:
                  - name: envoy.file_access_log
                    config:
                      path: /var/log/envoy/access.log
  clusters:
    - name: control
      connect_timeout: 0.25s
      http2_protocol_options: {}
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: control
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address: {address: control, port_value: 8080}

dynamic_resources:
  cds_config:
    api_config_source:
      api_type: GRPC
      grpc_services:
        envoy_grpc:
          cluster_name: control

node:
  cluster: color